### ISSUE TITLE
how to solve this error AttributeError: 'ModuleObj' object has no attribute 'modulefile' 

### ISSUE THREAD

**Issue by kush987** [NREL/bifacial_radiance#369]
Read all values

New bifacial_radiance simulation starting.
Version:  0.4.0+0.g8e40416.dirty
path = D:\b=new bif\bifacial_radiance\bifacial_radiance\TEMP
analysisParamsDict['modWanted'] set to middle module by default
analysisParamsDict['rowWanted'] set to middle row by default
d:\b=new bif\bifacial_radiance\bifacial_radiance\main.py:732: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dftemp, ignore_index=True)
Getting weather file: USA_AZ_Safford.AWOS.722747_TMY3.epw
 ... OK!
Reading weather file EPWs\USA_AZ_Safford.AWOS.722747_TMY3.epw
8760 line in WeatherFile. Assuming this is a standard hourly WeatherFile for the year for purposes of saving Gencumulativesky temporary weather files in EPW folder.
Coercing year to 2021
Saving file EPWs\metdata_temp.csv, # points: 8760
Calculating Sun position for Metdata that is right-labeled  with a delta of -30 mins. i.e. 12 is 11:30 sunpos
Loading albedo, 1 value(s), 0.620 avg
1 nonzero albedo values.
Available module names: ['PrismSolar-Bi60', 'Prism_Solar_Bi60', 'basic-module', 'test-module']

Module Name: Prism_Solar_Bi60
Module Prism_Solar_Bi60 updated in module.json
Pre-existing .rad file objects\Prism_Solar_Bi60.rad will be overwritten

Error: module name Prism Solar Bi60 doesnt exist
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\kushal.kumar\.conda\envs\bifi\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "D:\b=new bif\bifacial_radiance\bifacial_radiance\gui.py", line 390, in runBifacialRadiance
    self.data, self.analysis = bifacial_radiance.modelchain.runModelChain(simulationParamsDict=simulationParamsDict,
  File "d:\b=new bif\bifacial_radiance\bifacial_radiance\modelchain.py", line 140, in runModelChain
    scene = demo.makeScene(module=simulationParamsDict['moduletype'],
  File "d:\b=new bif\bifacial_radiance\bifacial_radiance\main.py", line 2110, in makeScene
    self.scene = SceneObj(module)
  File "d:\b=new bif\bifacial_radiance\bifacial_radiance\main.py", line 2811, in __init__
    self.module = ModuleObj(name=module)
  File "d:\b=new bif\bifacial_radiance\bifacial_radiance\module.py", line 110, in __init__
    self._saveModule(savedata=None, json=False,
  File "d:\b=new bif\bifacial_radiance\bifacial_radiance\module.py", line 276, in _saveModule
    if rewriteModulefile & os.path.isfile(self.modulefile):
AttributeError: 'ModuleObj' object has no attribute 'modulefile

**Comment by shirubana** [comment]
Kudos on finding our first bug!!

I wonder if it has something to do with the white spaces.. it saves "Prism Solar" but the Json has "Prism_Solar". Maybe while we fix this try using one word, or no spaces or dashes instead of spaces?

**Comment by kush987** [comment]
In bifacial repo is there any flat mirror or curve mirrors are using for
reflection

**Comment by shirubana** [comment]
There is mirror material on Radiance, or you can define a new material on bifacial radiance with very high reflectivity (addMaterial function).

The material can be defined for a flat surface or curved one, but specially for the curved surface you are going to have to go into the documentation of Radiance to find the right call and examples. Alternatively you could import a CAD. Our makeModule and makeScene support appended objects (code or cads), but not in the GUI.

Hope this helps


Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
