### ISSUE TITLE
How to Add or create a mirror reflector according to the panel position to calculate the Front and back side radiance??

### ISSUE THREAD

**Issue by kush987** [NREL/bifacial_radiance#372]
I need to add a new mirror reflector object to calculate the radiance

**Comment by shirubana** [comment]
Image didn't came through, you might need to paste into the issue directly through Github and not by mail (which seems to be the method)

https://github.com/NREL/bifacial_radiance/issues/372#issuecomment-1031566729

**Comment by kush987** [comment]
Like this image 
![images (2)](https://user-images.githubusercontent.com/97940710/152816749-3ff1ea57-e277-45cc-ad11-dc34c75eb754.jpeg)
Is it possible to integrate

**Comment by kush987** [comment]
And also like this image 
![Uploading images.png…]()

**Comment by kush987** [comment]
- I need to calculate the rear panel radiance 
- mirror could be curve or flat 
![energies-12-04602-g001-550](https://user-images.githubusercontent.com/97940710/152929081-1aac547e-294e-4a55-8355-70cd3863f794.jpg)

**Comment by yjkm** [comment]
A "perfect" mirror has an albedo of 1, so I would assume what you can do is set the albedo = 1 in the code or in the GUI - that will mean you will get a **flat** mirror. However, if that were to be the path that you go through, that would mean the "pitch" (row-to-row spacing) would all be covered by a mirror - which doesn't seem feasible in practice.

**Comment by kush987** [comment]
How does it work in the case of a curved mirror ??

**Comment by shirubana** [comment]
@yjkm  I just added a tutorial example (Tutorial 22) on development branch showing how to do your first image, I hope it helps.

Regarding curved mirror, you can import a CAD, or look into radiance code itself it does have some 'genrev' surfaces. However, using curved surfaces in the raytrace is not ideal as it tesellates the curvature, so you end up with WAY TOO MANY surfaces which slows down, and you might get some weird artifcats. I'd suggest approximating the curved surface by a good amount of flat surfaces placed properly to simulate the curve. More on this forum.  https://discourse.radiance-online.org/t/curved-mirror-surfaces/685

**Comment by kush987** [comment]
> Member

Can we reposition the mirror object as our requirement

**Comment by shirubana** [comment]
Yes. See the tutorial and calculate the position on where you want them.

**Comment by kush987** [comment]
> * I need to calculate the rear panel radiation
> * mirror could be curve or flat
>   ![energies-12-04602-g001-550](https://user-images.githubusercontent.com/97940710/152929081-1aac547e-294e-4a55-8355-70cd3863f794.jpg)

For this image we can follow the tutorial_22 ????

**Comment by kush987** [comment]
Your simulation will be stored in D:\new Bifacial\bifacial_radiance\bifacial_radiance\TEMP
path = D:\new Bifacial\bifacial_radiance\bifacial_radiance\TEMP
Loading albedo, 1 value(s), 0.200 avg
1 nonzero albedo values.
Getting weather file: USA_VA_Richmond.724010_TMY2.epw
 ... OK!
8760 line in WeatherFile. Assuming this is a standard hourly WeatherFile for the year for purposes of saving Gencumulativesky temporary weather files in 
EPW folder.
Coercing year to 2021
Saving file EPWs\metdata_temp.csv, # points: 8760
Calculating Sun position for Metdata that is right-labeled  with a delta of -30 mins. i.e. 12 is 11:30 sunpos

Module Name: test-module
Module test-module updated in module.json
Pre-existing .rad file objects\test-module.rad will be overwritten

Created tutorial_22.oct
Linescan in process: tutorial_22_Front
Linescan in process: tutorial_22_Back
Saved: results\irr_tutorial_22.csv
Result without mirror:  <module 'unittest.result' from 'C:\\Users\\kushal.kumar\\.conda\\envs\\bifi1\\lib\\unittest\\result.py'>
Material exists, overwriting...

Added material testmirror to file ground.rad

Module Name: test-mirror
Module test-mirror updated in module.json
Pre-existing .rad file objects\test-mirror.rad will be overwritten

Created tutorial_22.oct
Linescan in process: tutorial_22_withMirror_Front
message: rtrace: fatal - bad number of arguments for mirror "testmirror"
Linescan in process: tutorial_22_withMirror_Back
message: rtrace: fatal - bad number of arguments for mirror "testmirror"

(bifi1) D:\new Bifacial\bifacial_radiance\bifacial_radiance>python mirroring.py                                                                          
Your simulation will be stored in D:\new Bifacial\bifacial_radiance\bifacial_radiance\TEMP
path = D:\new Bifacial\bifacial_radiance\bifacial_radiance\TEMP
Loading albedo, 1 value(s), 0.200 avg
1 nonzero albedo values.
Getting weather file: USA_VA_Richmond.724010_TMY2.epw
 ... OK!
8760 line in WeatherFile. Assuming this is a standard hourly WeatherFile for the year for purposes of saving Gencumulativesky temporary weather files in 
EPW folder.
Coercing year to 2021
Saving file EPWs\metdata_temp.csv, # points: 8760
Calculating Sun position for Metdata that is right-labeled  with a delta of -30 mins. i.e. 12 is 11:30 sunpos

Module Name: test-module
Module test-module updated in module.json
Pre-existing .rad file objects\test-module.rad will be overwritten

Created tutorial_22.oct
Linescan in process: tutorial_22_Front
Linescan in process: tutorial_22_Back
Saved: results\irr_tutorial_22.csv
Result without mirror:  <module 'unittest.result' from 'C:\\Users\\kushal.kumar\\.conda\\envs\\bifi1\\lib\\unittest\\result.py'>
Material exists, overwriting...

Added material testmirror to file ground.rad

Module Name: test-mirror
Module test-mirror updated in module.json
Pre-existing .rad file objects\test-mirror.rad will be overwritten

Created tutorial_22.oct
Linescan in process: tutorial_22_withMirror_Front
message: rtrace: fatal - bad number of arguments for mirror "testmirror"
Linescan in process: tutorial_22_withMirror_Back
message: rtrace: fatal - bad number of arguments for mirror "testmirror"
Traceback (most recent call last):
  File "D:\new Bifacial\bifacial_radiance\bifacial_radiance\mirroring.py", line 146, in <module>
    withMirror = bifacial_radiance.load.read1Result('results\irr_tutorial_22_withMirror.csv')
  File "d:\new bifacial\bifacial_radiance\bifacial_radiance\load.py", line 164, in read1Result
    resultsDF = pd.read_csv(selectfile)
  File "C:\Users\kushal.kumar\.conda\envs\bifi1\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\kushal.kumar\.conda\envs\bifi1\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\kushal.kumar\.conda\envs\bifi1\lib\site-packages\pandas\io\parsers\readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\kushal.kumar\.conda\envs\bifi1\lib\site-packages\pandas\io\parsers\readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\kushal.kumar\.conda\envs\bifi1\lib\site-packages\pandas\io\parsers\readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "C:\Users\kushal.kumar\.conda\envs\bifi1\lib\site-packages\pandas\io\common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'results\\irr_tutorial_22_withMirror.csv' this error will come after running  the "Mirror_and_Module.py" file

**Comment by shirubana** [comment]
I suspect you don't have the latest version of development that fixed a bug on how the material gets saved; I published this bug fix with the journal, and it changes the number of arguments for primitives (materials) of 'mirror' type to 3. 

To confirm which version you are running ,pleas eprint

bifacial_radiance.__version__

It should be '0.4.0-dev2'       or something like that.

**Comment by kush987** [comment]
I have a question so this mirror is working like a mirror reflector. Or not????

**Comment by kush987** [comment]
> I suspect you don't have the latest version of development that fixed a bug on how the material gets saved; I published this bug fix with the journal, and it changes the number of arguments for primitives (materials) of 'mirror' type to 3.
> 
> To confirm which version you are running ,pleas eprint
> 
> bifacial_radiance.**version**
> 
> It should be '0.4.0-dev2' or something like that.

I have a question so this mirror is working like a mirror reflector. Or not????

**Comment by shirubana** [comment]
Yes, it is; is there another option or what is the question? If you notice on the example I provided there is a very big increase from including the mirror on the simulation vs no mirror; that is the sanity check.

You will have to play with the coordinates to create the mirror in the position you want for your example.
