### ISSUE TITLE
subprocess.py can't find the specific file

### ISSUE THREAD

**Issue by wt163** [NREL/bifacial_radiance#491]
Did anybody have the problem with makeOctfile, After I run octfile = demo.makeOct(demo.getfilelist()), then it showed the error can't find file. Even if I have changed the Shell=True.

Traceback (most recent call last):
  File "C:\Users\.conda\envs\pySMARTS_example\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-1a9cc2a0f22a>", line 5, in <module>
    octfile = demo.makeOct(filelist)
  File "C:\Users\Desktop\bifacial_radiance\bifacial_radiance\main.py", line 1895, in makeOct
    _,err = _popen(filelist, None, f)
  File "C:\Users\Desktop\bifacial_radiance\bifacial_radiance\main.py", line 100, in _popen
    p = Popen(cmd, bufsize=-1, stdin=PIPE, stdout=data_out, stderr=PIPE, shell=shell) #shell=True required for Linux? quick fix, but may be security concern
  File "C:\Users\.conda\envs\pySMARTS_example\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\.conda\envs\pySMARTS_example\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] System cannot find the specific file。

**Comment by cdeline** [comment]
This is almost certainly because the RADIANCE executables are not set up on your PATH directory.  Please follow the install instructions [here](https://bifacial-radiance.readthedocs.io/en/stable/user_guide/installation.html), and particularly pay attention to setting up the PATH and RAYPATH environment variables.
