### ISSUE TITLE
Deploy errors in development

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#566]
Both the tag name and the pypi deploy method are reporting errors.

Tag error v0.5.0-dev1:

 (bifiradiance) PS C:\Users\cdeline\Documents\Python Scripts\Bifacial_Radiance> pip install -e .
Obtaining file:///C:/Users/cdeline/Documents/Python%20Scripts/Bifacial_Radiance
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      C:\Users\cdeline\AppData\Roaming\Python\Python39\site-packages\setuptools\dist.py:788: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      C:\Users\cdeline\AppData\Roaming\Python\Python39\site-packages\setuptools\__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        
        File "C:\Users\cdeline\AppData\Roaming\Python\Python39\site-packages\setuptools_scm\version.py", line 244, in guess_next_version
          return _bump_dev(version) or _bump_regex(version)
        File "C:\Users\cdeline\AppData\Roaming\Python\Python39\site-packages\setuptools_scm\version.py", line 271, in _bump_dev
          raise ValueError(
      ValueError: choosing custom numbers for the `.devX` distance is not supported.
       The 0.5.0.dev1 can't be bumped
      Please drop the tag or create a new supported one ending in .dev0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by cdeline** [comment]
Github Actions deploy error message:

Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
